# enquete_vie_sociale_donnees_config.yml
theme: jekyll-theme-minimal
title: L'histoire de la base de données
description: Bookmark this to keep an eye on my project updates!



# les analyses de la base de données
## les interviews
### Les limites et les critiques de la base de données
